### ISSUE TITLE
Found unsupported required field type - `InputJsonValue | null`

### ISSUE THREAD

**Issue by OmarBish** [arthurfiorette/prisma-json-types-generator#142]
### versions: 
```
"@prisma/client": "5.1.1",
"prisma-json-types-generator": "^3.0.0-beta.4",
```

### Description: 
```
model sample {
   metadata Json?
}
```

if you try to run generate with an optional json field you will get the following error
```
PrismaJsonTypesGeneratorError: Found unsupported required field type
    at findNewSignature (...monorepo/node_modules/prisma-json-types-generator/src/helpers/find-signature.ts:161:15)
    at replaceObject (...monorepo/node_modules/prisma-json-types-generator/src/handler/replace-object.ts:52:44)
    at handleStatement (...monorepo/node_modules/prisma-json-types-generator/src/handler/statement.ts:41:29)
    at handlePrismaModule (...monorepo/node_modules/prisma-json-types-generator/src/handler/module.ts:38:22)
    at ...monorepo/node_modules/prisma-json-types-generator/src/on-generate.ts:41:27
    at visitNodes (...monorepo/node_modules/typescript/lib/typescript.js:31214:30)
    at forEachChildInSourceFile (...monorepo/node_modules/typescript/lib/typescript.js:31573:20)
    at Object.forEachChild (...monorepo/node_modules/typescript/lib/typescript.js:31988:47)
    at SourceFileObject.NodeObject.forEachChild (...monorepo/node_modules/typescript/lib/typescript.js:168280:23)
    at Object.onGenerate (...monorepo/node_modules/prisma-json-types-generator/src/on-generate.ts:38:12) {
  signature: 'InputJsonValue | null',
  typeToChange: 'PrismaJson.SampleMetadata',
  type: 'sample',
  fieldName: 'metadata',
  throwOnNotFound: true
}
```
I know that it's still in beta but I saw your comment in https://github.com/prisma/prisma/issues/3219#issuecomment-1679017657 , and can be considered stable. so I thought it's worth mentioning this to maintainers attention .

thank you fro the great hack really life saving🙏

**Comment by OmarBish** [comment]
hey @arthurfiorette 
you can check this repo , it has minimal prisma setup and can reproduce the issue. 
https://github.com/OmarBish/prisma-json-types-generator-sample

**Comment by arthurfiorette** [comment]
Hey @OmarBish, thanks for creating the repo! Fixed the issue and will release v3 with it asap.
